name: Build Theme (Development)

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  build-theme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Verify theme metadata
        run: |
          echo "=== Current komari-theme.json content ==="
          cat komari-theme.json
          echo "=================================="
      
      - name: Run tests
        run: |
          # Run tests if available
          if [ -f "package.json" ] && grep -q "\"test\":" package.json; then
            npm test || echo "Tests failed, but continuing..."
          fi
      
      - name: Build theme
        run: |
          chmod +x build-theme.sh
          ./build-theme.sh
      
      - name: Get version info
        id: version
        run: |
          VERSION_DATE=$(date +"%y.%m.%d")
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "version=${VERSION_DATE}" >> $GITHUB_OUTPUT
          echo "commit=${COMMIT_HASH}" >> $GITHUB_OUTPUT
          echo "branch=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          echo "filename=komari-theme-v${VERSION_DATE}-${COMMIT_HASH}.zip" >> $GITHUB_OUTPUT
      
      - name: Extract theme for artifact upload
        run: |
          mkdir -p theme-artifact
          unzip ${{ steps.version.outputs.filename }} -d theme-artifact
          
      - name: Upload theme artifact
        uses: actions/upload-artifact@v4
        with:
          name: theme-${{ steps.version.outputs.branch }}-${{ steps.version.outputs.version }}-${{ steps.version.outputs.commit }}
          path: |
            theme-artifact/komari-theme.json
            theme-artifact/preview.png
            theme-artifact/dist/
          retention-days: 7
      
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const version = '${{ steps.version.outputs.version }}';
            const commit = '${{ steps.version.outputs.commit }}';
            const filename = '${{ steps.version.outputs.filename }}';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🎨 Theme Build Successful!\n\n**Version:** ${version}\n**Commit:** ${commit}\n\n📦 **Theme package:** \`${filename}\`\n\nThe theme package has been built successfully and is available as an artifact in this workflow run.`
            })
      
      - name: Build Summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version:** ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** ${{ steps.version.outputs.commit }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** ${{ steps.version.outputs.branch }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Theme Package:** ${{ steps.version.outputs.filename }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Theme built successfully!" >> $GITHUB_STEP_SUMMARY